"""
This module contains the prompt templates used to generate descriptions with the LLM.

Each constant is a formatted string that provides context and instructions to the language model
for generating meaningful descriptions for database columns, dbt models, and dbt columns.
"""

# Prompt template for generating a description for a database column.
# This prompt asks the LLM to provide a brief, business-focused meaning of the column.
COLUMN_DESCRIPTION_PROMPT = """  
Briefly describe the business meaning of the '{col_name}' ({col_type}) column in table '{table_name}' in under 15 characters.  
(Example: Unique identifier of a user)  
"""

# Prompt template for generating a summary for a dbt model.
# This prompt provides the model's SQL code and asks the LLM to summarize its business purpose.
DBT_MODEL_PROMPT = """  
You are a dbt expert.  
Below is the SQL query that defines the '{model_name}' dbt model.  
Summarize in 1-2 sentences what kind of data this model produces or aggregates from a business perspective.  

```sql
{raw_sql}
```  
"""

DBT_MODEL_LINEAGE_PROMPT = """
You are a data architect specializing in dbt.
Below is the SQL query that defines the '{model_name}' dbt model.
Analyze the `ref()` and `source()` functions to understand its dependencies.

Generate a Mermaid.js `graph TD` (Top-Down) flowchart code that shows the lineage for this *single* model.
- Show only the direct parents (sources or refs) flowing *into* this model.
- Do not show downstream children.
- Keep it simple.

SQL:
```sql
{raw_sql}
```

---
EXAMPLE INPUT (SQL):
with orders as (
    select * from {{ ref('stg_orders') }}
),
payments as (
    select * from {{ ref('stg_payments') }}
)
select ... from orders join payments ...
---
EXAMPLE OUTPUT (Mermaid code ONLY):
```mermaid
graph TD
    A[stg_orders] --> C({model_name});
    B[stg_payments] --> C({model_name});
```
"""

# Prompt template for generating a description for a dbt column.
# This prompt provides the model's SQL and column details, asking for a concise business description.
DBT_COLUMN_PROMPT = """
You are a senior data governance expert using dbt.
Analyze the column '{col_name}' ({col_type}) in the dbt model '{model_name}'.
This column is generated by the following SQL:

SQL context:
```sql
{raw_sql}
```

Your task is to generate a YAML snippet for a dbt `schema.yml` file.
Provide the following keys:
1.  `description`: A concise (under 20 words) business description of this column.
2.  `meta`: A meta field containing `pii: true` if the column name or context suggests it's Personally Identifiable Information (e.g., email, name, phone, ssn), otherwise `pii: false`.
3.  `tags`: A YAML list of 1-2 relevant business tags (e.g., 'user_info', 'finance', 'pii').
4.  `tests`: A YAML list of 1-2 appropriate dbt generic tests (e.g., 'not_null', 'unique'). If no specific test seems necessary, provide an empty list `[]`.

Output ONLY the YAML snippet, starting with `description:`.
Do not include any other text, explanations, or markdown fences.

---
EXAMPLE INPUT (col_name='email'):
---
EXAMPLE OUTPUT:
description: The user's unique email address for login and contact.
meta:
  pii: true
tags:
  - user_info
  - pii
tests:
  - not_null
  - unique
"""
