"""
This module centralizes all prompt templates used for generating content with the LLM.

Each constant is a carefully formatted f-string that provides context, instructions,
and few-shot examples to the language model. This helps ensure the model's output
is structured and relevant for tasks like generating column descriptions, model summaries,
and dbt metadata.
"""

# Prompt template for generating a description for a database column.
# This prompt asks the LLM to act as a business analyst and provide a brief,
# business-focused meaning of a database column.
# Placeholders:
# - {col_name}: The name of the column.
# - {col_type}: The data type of the column.
# - {table_name}: The name of the table the column belongs to.
COLUMN_DESCRIPTION_PROMPT = """  
Briefly describe the business meaning of the '{col_name}' ({col_type}) column in table '{table_name}' in under 15 characters.  
(Example: Unique identifier of a user)  
"""

# Prompt template for generating a high-level summary for a dbt model.
# This prompt provides the model's raw SQL code and asks the LLM to act as a
# dbt expert and summarize its business purpose.
# Placeholders:
# - {model_name}: The name of the dbt model.
# - {raw_sql}: The raw SQL code that defines the model.
DBT_MODEL_PROMPT = """  
You are a dbt expert.  
Below is the SQL query that defines the '{model_name}' dbt model.  
Summarize in 1-2 sentences what kind of data this model produces or aggregates from a business perspective.  

```sql
{raw_sql}
```  
"""

# Prompt template for generating a Mermaid.js lineage chart for a dbt model.
# This prompt asks the LLM to act as a data architect, analyze the model's
# dependencies (`ref` and `source` functions), and generate a simple, top-down
# Mermaid graph showing only its direct parents.
# Placeholders:
# - {model_name}: The name of the dbt model.
# - {raw_sql}: The raw SQL code that defines the model.
DBT_MODEL_LINEAGE_PROMPT = """
You are a data architect specializing in dbt.
Below is the SQL query that defines the '{model_name}' dbt model.
Analyze the `ref()` and `source()` functions to understand its dependencies.

Generate a Mermaid.js `graph TD` (Top-Down) flowchart code that shows the lineage for this *single* model.
- Show only the direct parents (sources or refs) flowing *into* this model.
- Do not show downstream children.
- Keep it simple.

SQL:
```sql
{raw_sql}
```

---
EXAMPLE INPUT (SQL):
with orders as (
    select * from {{ ref('stg_orders') }}
),
payments as (
    select * from {{ ref('stg_payments') }}
)
select ... from orders join payments ...
---
EXAMPLE OUTPUT (Mermaid code ONLY):
```mermaid
graph TD
    A[stg_orders] --> C({model_name});
    B[stg_payments] --> C({model_name});
```
"""

VIEW_SUMMARY_PROMPT = """
You are a professional data analyst.
Below is the SQL query that defines the database view '{view_name}'.
Summarize in 1-2 sentences what business-level information this view provides.

```sql
{view_definition}
```
"""

# Prompt template for generating a complete YAML metadata block for a dbt column.
# This prompt asks the LLM to act as a senior data governance expert and generate
# a YAML snippet containing a description, PII metadata, tags, and appropriate tests.
# It is designed to produce output that can be directly used in a dbt `schema.yml` file.
# Placeholders:
# - {col_name}: The name of the column.
# - {col_type}: The data type of the column.
# - {model_name}: The name of the dbt model.
# - {raw_sql}: The raw SQL code of the model for context.
DBT_COLUMN_PROMPT = """
You are a senior data governance expert using dbt.
Analyze the column '{col_name}' ({col_type}) in the dbt model '{model_name}'.
This column is generated by the following SQL:

SQL context:
```sql
{raw_sql}
```

Your task is to generate a YAML snippet for a dbt `schema.yml` file.
Provide the following keys:
1.  `description`: A concise (under 20 words) business description of this column.
2.  `meta`: A meta field containing `pii: true` if the column name or context suggests it's Personally Identifiable Information (e.g., email, name, phone, ssn), otherwise `pii: false`.
3.  `tags`: A YAML list of 1-2 relevant business tags (e.g., 'user_info', 'finance', 'pii').
4.  `tests`: A YAML list of 1-2 appropriate dbt generic tests (e.g., 'not_null', 'unique'). If no specific test seems necessary, provide an empty list `[]`.

Output ONLY the YAML snippet, starting with `description:`.
Do not include any other text, explanations, or markdown fences.

---
EXAMPLE INPUT (col_name='email'):
---
EXAMPLE OUTPUT:
description: The user's unique email address for login and contact.
meta:
  pii: true
tags:
  - user_info
  - pii
tests:
  - not_null
  - unique
"""
